apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-canary
  namespace: mern-app
  labels:
    app: backend
    track: canary
    version: v2
spec:
  replicas: 1   # 10% traffic (1 canary : 9 stable pods)
  selector:
    matchLabels:
      app: backend
      track: canary
  template:
    metadata:
      labels:
        app: backend
        track: canary
        version: v2
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
    spec:
      containers:
        - name: backend
          image: YOUR_ECR_REPO/mern-backend:v2
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: backend-config
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
          readinessProbe:
            httpGet:
              path: /ready
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
